apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: bajajtraining
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: sinansin/microservicedocker:latest
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
   name: microservice
   namespace: bajajtraining
spec:
  selector:
    app: my-app-deployment
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080